import { BMP180_DEVICE_PACKAGE_SOURCE } from './bmp180';
import { SI7021_DEVICE_PACKAGE_SOURCE } from './si7021';
import { SSD1306_DEVICE_PACKAGE_SOURCE } from './ssd1306';
import { UART_TERMINAL_DEVICE_PACKAGE_SOURCE } from './uart-terminal';
import { GENERATED_RENODE_NATIVE_DEVICE_PACKAGE_SOURCES } from '../../src/lib/renode-native-device-package-generator';

export const DEVICE_PACKAGE_SOURCES = [
  SSD1306_DEVICE_PACKAGE_SOURCE,
  SI7021_DEVICE_PACKAGE_SOURCE,
  BMP180_DEVICE_PACKAGE_SOURCE,
  UART_TERMINAL_DEVICE_PACKAGE_SOURCE,
  ...GENERATED_RENODE_NATIVE_DEVICE_PACKAGE_SOURCES,
] as const;

export {
  BMP180_DEVICE_PACKAGE_SOURCE,
  GENERATED_RENODE_NATIVE_DEVICE_PACKAGE_SOURCES,
  SI7021_DEVICE_PACKAGE_SOURCE,
  SSD1306_DEVICE_PACKAGE_SOURCE,
  UART_TERMINAL_DEVICE_PACKAGE_SOURCE,
};
