import { BMP180_DEVICE_PACKAGE_SOURCE } from './bmp180';
import { SI7021_DEVICE_PACKAGE_SOURCE } from './si7021';
import { SSD1306_DEVICE_PACKAGE_SOURCE } from './ssd1306';
import { UART_TERMINAL_DEVICE_PACKAGE_SOURCE } from './uart-terminal';

export const DEVICE_PACKAGE_SOURCES = [
  SSD1306_DEVICE_PACKAGE_SOURCE,
  SI7021_DEVICE_PACKAGE_SOURCE,
  BMP180_DEVICE_PACKAGE_SOURCE,
  UART_TERMINAL_DEVICE_PACKAGE_SOURCE,
] as const;

export {
  BMP180_DEVICE_PACKAGE_SOURCE,
  SI7021_DEVICE_PACKAGE_SOURCE,
  SSD1306_DEVICE_PACKAGE_SOURCE,
  UART_TERMINAL_DEVICE_PACKAGE_SOURCE,
};
