import type { DevicePackageSource } from '../../../src/lib/device-package-types';

export const SI7021_DEVICE_PACKAGE_SOURCE = {
  source: {
    packagePath: 'packages/devices/si7021',
    componentPackageKind: 'si7021-sensor',
    sensorPackageKind: 'si7021-sensor',
  },
  kind: 'si7021-sensor',
  title: 'SI7021 Sensor',
  subtitle: 'I2C temperature/humidity',
  description:
    'A Renode SI70xx-compatible I2C sensor endpoint with adjustable temperature and humidity readings.',
  version: '1.0.0',
  category: 'sensor',
  visual: {
    icon: 'sensor',
    accentColor: '#34d399',
    defaultWidth: 168,
    defaultHeight: 104,
    terminalLayout: 'explicit-endpoints',
    library: {
      visible: true,
      order: 200,
      group: 'Sensors',
      draggable: true,
      addMode: 'legacy-template',
    },
  },
  pins: [
    {
      id: 'scl',
      label: 'SCL',
      role: 'i2c-scl',
      direction: 'bidirectional',
      requiredPadCapabilities: ['gpio', 'i2c-scl'],
      netKind: 'i2c',
      protocols: ['i2c'],
      terminal: {
        side: 'top',
        order: 0,
        handleId: 'si7021-sensor:scl',
        connectable: true,
        dragGesture: 'terminal-to-board-pad',
      },
    },
    {
      id: 'sda',
      label: 'SDA',
      role: 'i2c-sda',
      direction: 'bidirectional',
      requiredPadCapabilities: ['gpio', 'i2c-sda'],
      netKind: 'i2c',
      protocols: ['i2c'],
      terminal: {
        side: 'top',
        order: 1,
        handleId: 'si7021-sensor:sda',
        connectable: true,
        dragGesture: 'terminal-to-board-pad',
      },
    },
    {
      id: 'vcc',
      label: 'VCC',
      role: 'power-vcc',
      direction: 'bidirectional',
      requiredPadCapabilities: ['power-vcc'],
      netKind: 'power',
      protocols: ['power'],
      terminal: {
        side: 'bottom',
        order: 0,
        handleId: 'si7021-sensor:vcc',
        connectable: true,
        dragGesture: 'terminal-to-board-pad',
      },
    },
    {
      id: 'gnd',
      label: 'GND',
      role: 'power-gnd',
      direction: 'bidirectional',
      requiredPadCapabilities: ['ground'],
      netKind: 'ground',
      protocols: ['ground'],
      terminal: {
        side: 'bottom',
        order: 1,
        handleId: 'si7021-sensor:gnd',
        connectable: true,
        dragGesture: 'terminal-to-board-pad',
      },
    },
  ],
  electricalRules: {
    requiresPower: true,
    requiresGround: true,
    voltageDomains: ['3v3', '5v'],
    compatibleProtocols: ['i2c', 'power', 'ground'],
    busPairing: 'i2c-scl-sda',
    outputContention: 'not-applicable',
  },
  protocol: {
    primary: 'i2c',
    buses: ['i2c'],
    addressMode: 'seven-bit',
    defaultAddress: 0x40,
    transactionModel: 'mcu-initiated-i2c',
  },
  renodeBackend: {
    type: 'renode-native-sensor',
    manifest: 'runtime-bus-manifest',
    model: 'si7021',
    address: 0x40,
    nativeRenodeType: 'Sensors.SI70xx',
    nativeControlTransport: 'renode-monitor-property',
    sensorPackage: 'si7021-sensor',
  },
  runtimePanel: {
    controls: ['sensor-control', 'sensor-inspector'],
    visualizers: ['bus-transactions', 'uart-terminal', 'runtime-timeline'],
    eventParsers: ['bus-transaction', 'i2c-si70xx-measurement', 'uart-line-buffer'],
  },
  exampleFirmware: {
    mode: 'generated-i2c-demo',
    generatedDriver: 'generated-i2c-read-driver',
    requiredIncludes: ['stdint.h'],
  },
  validationFixture: {
    representative: 'i2c-sensor',
    expectedManifest: 'runtime-bus-manifest',
    expectedPanels: ['sensor-control', 'bus-transactions', 'uart-terminal'],
    smokeExampleId: 'nucleo-h753zi-si7021-sensor',
  },
} as const satisfies DevicePackageSource;

export default SI7021_DEVICE_PACKAGE_SOURCE;
